/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package winterbreakstudying.Cookbook;

import java.util.ArrayList;

public class Cookbook {

  // Create an private instance variable
  // It is an arrayList of all the foods this cookbook contains

  // Create a zero arg constructor
  public Cookbook() {}

  // Create a multi arg constructor
  public Cookbook(ArrayList<Food> foods) {}

  // Returns the arraylist of all the food
  public ArrayList<Food> getFoods() {
    return new ArrayList<>();
  }

  // Iterate through the array and print all the food names
  public void printNamesOfAllDishes() {}

  // Should find the highest rated dish and return it
  // If there are two dishes both most highly rated, then this method should return the first dish
  public Food findHighestRatedDish() {
    return new Food();
  }

  /**
   * Deletes all dishes below a certain rating (keeps the dishes greater than or equal to the min
   * rating) You shouldn't be setting the foods arraylist to something - no food = arraylist and no
   * arraylist.add() To should be using the .delete() method! Hint: inside a for-loop, you can
   * actually modify the index by going i = num; or i--; or i++; or whatever it's not great
   * practice, but you should use it for this situation
   *
   * @param minRating - the minimum rating for the new cookbook
   */
  public void purgeCookbook(double minRating) {}
}
