/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package winterbreakstudying.Cookbook;

import java.util.ArrayList;
import java.util.List;

public class Cookbook {

  // Create an private instance variable
  // It is an arrayList of all the foods this cookbook contains
  private ArrayList<Food> foods = new ArrayList<>();
  // Create a zero arg constructor
  public Cookbook() {
    foods = new ArrayList<Food>(List.of(
      new Food(),
      new Food("fried rice", 0.5, new String[]{"rice", "veggies", "soy sauce", "eggs"}, 5.0),
      new Food("steak", 1.0, new String[]{"salt", "butter", "steak", "herbs"}, 4.5)
    ));
  }

  // Create a multi arg constructor
  public Cookbook(ArrayList<Food> foods) {
    this.foods = foods;
  }

  // Returns the arraylist of all the food
  public ArrayList<Food> getFoods() {
    return foods;
  }

  // Iterate through the array and print all the food names
  public void printNamesOfAllDishes() {
    for (int i = 0; i < foods.size(); i++){
      System.out.println(foods.get(i).getName());
    }
  }

  // Should find the highest rated dish and return it
  // If there are two dishes both most highly rated, then this method should return the first dish
  public Food findHighestRatedDish() {
    Food highestRatedDish = foods.get(0);
    for (int i = 0; i < foods.size(); i++){
      if (foods.get(i).getRating() > highestRatedDish.getRating()){
        highestRatedDish = foods.get(i);
      }
    }
    return highestRatedDish;
  }

  /**
   * Deletes all dishes below a certain rating (keeps the dishes greater than or equal to the min
   * rating) You shouldn't be setting the foods arraylist to something - no food = arraylist and no
   * arraylist.add() To should be using the .delete() method! Hint: inside a for-loop, you can
   * actually modify the index by going i = num; or i--; or i++; or whatever it's not great
   * practice, but you should use it for this situation
   *
   * @param minRating - the minimum rating for the new cookbook
   */
  public void purgeCookbook(double minRating) {
    for (int i = 0; i < foods.size(); i++){
      if (foods.get(i).getRating() < minRating){
        foods.remove(i);
      }
    }
  }
}
