/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package winterbreakstudying;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;

import org.junit.jupiter.api.Test;
import winterbreakstudying.ArrayPractice.ArrayPractice;
import winterbreakstudying.Solutions.ArrayPracticeSolutions;

public class ArrayPracticeTest {

  private int[] testArr1 = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};

  private int[] expected1 = {0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0};

  private int[] expectedNoZeros1 = {7, 14};

  @Test
  public void arrayPracticeSolutionsWork() {

    assertArrayEquals(expected1, ArrayPracticeSolutions.findDivisibleBySevenSolution(testArr1));

    assertArrayEquals(
        expectedNoZeros1, ArrayPracticeSolutions.findDivisibleBySevenSolutionNoZeros1(testArr1));

    assertArrayEquals(
        expectedNoZeros1, ArrayPracticeSolutions.findDivisibleBySevenSolutionNoZeros2(testArr1));
  }

  @Test
  public void studentMethodsCorrectGeneral() {
    assertArrayEquals(expected1, ArrayPractice.findDivisibleBySeven(testArr1));

    assertArrayEquals(expectedNoZeros1, ArrayPractice.findDivisibleBySevenNoZeros(testArr1));
  }

  @Test
  public void randomStudentTests() {

    for (int i = 0; i < 20; i++) {

      int arrLength = (int) (Math.random() * 17 + 1);

      int[] randomArray = new int[arrLength];

      for (int k = 0; k < arrLength; k++) {
        randomArray[k] = (int) (Math.random() * 100 + 1);
      }

      assertArrayEquals(
          ArrayPracticeSolutions.findDivisibleBySevenSolution(randomArray),
          ArrayPractice.findDivisibleBySeven(randomArray));
    }
  }
}
