/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package winterbreakstudying;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

public class GradebookTest {
  @Test
  public void someLibraryMethodReturnsTrue() {
    Gradebook classUnderTest = new Gradebook();
    assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    assertTrue(false, "meow");
  }
}
